-- PIZZA SALES QUERY

/*  
1. Write a SQL query to calculate the total revenue generated from all pizza sales.
2. Write a SQL query to calculate the average order value for all pizza orders.
3. Write a SQL query to calculate the total number of pizzas sold.
4. Write a SQL query to calculate the total number of distinct orders placed.
5. Write a SQL query to calculate the average number of pizzas sold per order.
6. Write a SQL query to find the daily trend of total orders based on the day of the week.
7. Write a SQL query to find the hourly trend of total orders based on the order time.
8. Write a SQL query to calculate the percentage of total sales contributed by each pizza category.
9. Write a SQL query to calculate the percentage of total sales contributed by each pizza size.
10. Write a SQL query to find the total number of pizzas sold in each pizza category during the month of February.
11. Write a SQL query to identify the top 5 best-selling pizzas based on the total quantity sold.
12. Write a SQL query to identify the bottom 5 least-selling pizzas based on the total quantity sold.
13. Write a SQL query to find the daily trend of total orders for the month of January.
14. Write a SQL query to find the daily trend of total orders for Quarter 1.
15. Write a SQL query to find the total number of orders placed in each month.
16. Write a SQL query to find the total revenue generated in each quarter of the year.
17. Write a SQL query to identify the pizza category with the highest total sales.
18. Write a SQL query to identify the pizza size with the highest number of orders.
19. Write a SQL query to find the total quantity sold for each pizza name.
20. Write a SQL query to find the average quantity of pizzas ordered per order.
21. Write a SQL query to calculate the percentage contribution of each pizza category to the total quantity sold.
22. Write a SQL query to calculate the percentage contribution of each pizza size to the total quantity sold.
23. Write a SQL query to find the top 3 days with the highest number of orders.
24. Write a SQL query to find the top 3 hours with the highest number of orders.
25. Write a SQL query to find the month in which the maximum revenue was generated.
26. Write a SQL query to find the pizza category that sold the least number of pizzas.
27. Write a SQL query to find the pizza name that generated the highest revenue.
28. Write a SQL query to find the pizza name that generated the lowest revenue.
29. Write a SQL query to find the total number of orders placed for each pizza size.
30. Write a SQL query to find the total revenue generated by each pizza category and sort the result in descending order.
*/


# Pizza Sales SQL – 30 Questions with Answers

-- 1. Write a SQL query to calculate the total revenue generated from all pizza sales.

SELECT SUM(total_price) AS total_revenue
FROM pizza_sales;


-- 2. Write a SQL query to calculate the average order value for all pizza orders.

SELECT SUM(total_price) / COUNT(DISTINCT order_id) AS avg_order_value
FROM pizza_sales;

-- 3. Write a SQL query to calculate the total number of pizzas sold.

SELECT SUM(quantity) AS total_pizzas_sold
FROM pizza_sales;

-- 4. Write a SQL query to calculate the total number of distinct orders placed.

SELECT COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales;

-- 5. Write a SQL query to calculate the average number of pizzas sold per order.

SELECT ROUND(SUM(quantity) / COUNT(DISTINCT order_id), 2) AS avg_pizzas_per_order
FROM pizza_sales;

-- 6. Write a SQL query to find the daily trend of total orders based on the day of the week.

SELECT DAYNAME(order_date) AS order_day,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
GROUP BY DAYNAME(order_date);

-- 7. Write a SQL query to find the hourly trend of total orders based on the order time.

SELECT HOUR(order_time) AS order_hour,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
GROUP BY HOUR(order_time)
ORDER BY HOUR(order_time);


-- 8. Write a SQL query to calculate the percentage of total sales contributed by each pizza category.

SELECT pizza_category,
       SUM(total_price) AS total_revenue,
       ROUND(SUM(total_price) * 100 / (SELECT SUM(total_price) FROM pizza_sales), 2) AS sales_percentage
FROM pizza_sales
GROUP BY pizza_category;

-- 9. Write a SQL query to calculate the percentage of total sales contributed by each pizza size.

SELECT pizza_size,
       SUM(total_price) AS total_revenue,
       ROUND(SUM(total_price) * 100 / (SELECT SUM(total_price) FROM pizza_sales), 2) AS sales_percentage
FROM pizza_sales
GROUP BY pizza_size
ORDER BY pizza_size;

-- 10. Write a SQL query to find the total number of pizzas sold in each pizza category during the month of February.

SELECT pizza_category,
       SUM(quantity) AS total_quantity_sold
FROM pizza_sales
WHERE MONTH(order_date) = 2
GROUP BY pizza_category
ORDER BY total_quantity_sold DESC;

-- 11. Write a SQL query to identify the top 5 best-selling pizzas based on the total quantity sold.

SELECT pizza_name,
       SUM(quantity) AS total_pizzas_sold
FROM pizza_sales
GROUP BY pizza_name
ORDER BY total_pizzas_sold DESC
LIMIT 5;

-- 12. Write a SQL query to identify the bottom 5 least-selling pizzas based on the total quantity sold.

SELECT pizza_name,
       SUM(quantity) AS total_pizzas_sold
FROM pizza_sales
GROUP BY pizza_name
ORDER BY total_pizzas_sold ASC
LIMIT 5;

-- 13. Write a SQL query to find the daily trend of total orders for the month of January.

SELECT DAYNAME(order_date) AS order_day,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
WHERE MONTH(order_date) = 1
GROUP BY DAYNAME(order_date);

-- 14. Write a SQL query to find the daily trend of total orders for Quarter 1.

SELECT DAYNAME(order_date) AS order_day,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
WHERE QUARTER(order_date) = 1
GROUP BY DAYNAME(order_date);

-- 15. Write a SQL query to find the total number of orders placed in each month.

SELECT MONTH(order_date) AS month_number,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
GROUP BY MONTH(order_date)
ORDER BY MONTH(order_date);


-- 16. Write a SQL query to find the total revenue generated in each quarter of the year.

SELECT QUARTER(order_date) AS quarter_number,
       SUM(total_price) AS total_revenue
FROM pizza_sales
GROUP BY QUARTER(order_date)
ORDER BY QUARTER(order_date);

-- 17. Write a SQL query to identify the pizza category with the highest total sales.

SELECT pizza_category,
       SUM(total_price) AS total_sales
FROM pizza_sales
GROUP BY pizza_category
ORDER BY total_sales DESC
LIMIT 1;

-- 18. Write a SQL query to identify the pizza size with the highest number of orders.

SELECT pizza_size,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
GROUP BY pizza_size
ORDER BY total_orders DESC
LIMIT 1;

-- 19. Write a SQL query to find the total quantity sold for each pizza name.

SELECT pizza_name,
       SUM(quantity) AS total_quantity_sold
FROM pizza_sales
GROUP BY pizza_name
ORDER BY total_quantity_sold DESC;

-- 20. Write a SQL query to find the average quantity of pizzas ordered per order.

SELECT order_id,
       AVG(quantity) AS avg_quantity
FROM pizza_sales
GROUP BY order_id;

-- 21. Write a SQL query to calculate the percentage contribution of each pizza category to the total quantity sold.

SELECT pizza_category,
       SUM(quantity) AS total_quantity,
       ROUND(SUM(quantity) * 100 / (SELECT SUM(quantity) FROM pizza_sales), 2) AS percentage_contribution
FROM pizza_sales
GROUP BY pizza_category;


-- 22. Write a SQL query to calculate the percentage contribution of each pizza size to the total quantity sold.

SELECT pizza_size,
       SUM(quantity) AS total_quantity,
       ROUND(SUM(quantity) * 100 / (SELECT SUM(quantity) FROM pizza_sales), 2) AS percentage_contribution
FROM pizza_sales
GROUP BY pizza_size;


-- 23. Write a SQL query to find the top 3 days with the highest number of orders.

SELECT DAYNAME(order_date) AS order_day,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
GROUP BY DAYNAME(order_date)
ORDER BY total_orders DESC
LIMIT 3;

-- 24. Write a SQL query to find the top 3 hours with the highest number of orders.

SELECT HOUR(order_time) AS order_hour,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
GROUP BY HOUR(order_time)
ORDER BY total_orders DESC
LIMIT 3;

-- 25. Write a SQL query to find the month in which the maximum revenue was generated.

SELECT MONTH(order_date) AS month_number,
       SUM(total_price) AS total_revenue
FROM pizza_sales
GROUP BY MONTH(order_date)
ORDER BY total_revenue DESC
LIMIT 1;

-- 26. Write a SQL query to find the pizza category that sold the least number of pizzas.

SELECT pizza_category,
       SUM(quantity) AS total_quantity_sold
FROM pizza_sales
GROUP BY pizza_category
ORDER BY total_quantity_sold ASC
LIMIT 1;

-- 27. Write a SQL query to find the pizza name that generated the highest revenue.

SELECT pizza_name,
       SUM(total_price) AS total_revenue
FROM pizza_sales
GROUP BY pizza_name
ORDER BY total_revenue DESC
LIMIT 1;

-- 28. Write a SQL query to find the pizza name that generated the lowest revenue.

SELECT pizza_name,
       SUM(total_price) AS total_revenue
FROM pizza_sales
GROUP BY pizza_name
ORDER BY total_revenue ASC
LIMIT 1;

-- 29. Write a SQL query to find the total number of orders placed for each pizza size.

SELECT pizza_size,
       COUNT(DISTINCT order_id) AS total_orders
FROM pizza_sales
GROUP BY pizza_size     
ORDER BY total_orders DESC;   

-- 30. Write a SQL query to find the total revenue generated by each pizza category and sort the result in descending order.

SELECT pizza_category,
       SUM(total_price) AS total_revenue
FROM pizza_sales
GROUP BY 1
ORDER BY total_revenue DESC


--  






